fix: rosetta `getHeight` function to use tmRPC.GenesisChunked() instead tmRPC.Genesis() (backport #10340) (#10399)
* fix: rosetta `getHeight` function to use tmRPC.GenesisChunked() instead tmRPC.Genesis() (#10340)

<!--
The default pull request template is for types feat, fix, or refactor.
For other templates, add one of the following parameters to the url:
- template=docs.md
- template=other.md
-->

## Description

When we enable rosetta from the chain with non-zero initial height & huge genesis, it always return
```
Error: rosetta: (502) bad gateway
```

This is due to huge genesis load rejection from Tendermint.

In current implementation, rosetta server requests genesis to get initial height
```
c.tmRPC.Genesis(ctx)
```

but, this will be failed with below message when the genesis is huge
```
{
  "jsonrpc": "2.0",
  "id": -1,
  "error": {
    "code": -32603,
    "message": "Internal error",
    "data": "genesis response is large, please use the genesis_chunked API instead"
  }
}
```

To fix this, we can use following lines
```
status, err := c.tmRPC. GenesisChunked(ctx)

```